import React from "react";
const Packages = [
  {
    title: "service1",
    packages: [
      {
        title: "starterPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 5 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "no",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "no",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "no",
        WebsiteVisitorStatistics: "no",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "no",
        EmailAddresses: "no",
        FreeDomainNamefor1year: "no",
        FreeWebsitehostingfor1year: "no",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },

      {
        title: "advancedPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 10 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 5 Pages",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
      {
        title: "enterprisePackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 20 Pages",
        Updateandaddpages: "yes",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 10 Pages",
        ProfessionalLogDesign: "yes",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
    ],
  },
  {
    title: "service2",
    packages: [
      {
        title: "starterPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 5 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "no",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "no",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "no",
        WebsiteVisitorStatistics: "no",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "no",
        EmailAddresses: "no",
        FreeDomainNamefor1year: "no",
        FreeWebsitehostingfor1year: "no",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },

      {
        title: "advancedPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 10 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 5 Pages",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
      {
        title: "enterprisePackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 20 Pages",
        Updateandaddpages: "yes",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 10 Pages",
        ProfessionalLogDesign: "yes",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
    ],
  },
  {
    title: "service3",
    packages: [
      {
        title: "starterPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 5 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "no",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "no",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "no",
        WebsiteVisitorStatistics: "no",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "no",
        EmailAddresses: "no",
        FreeDomainNamefor1year: "no",
        FreeWebsitehostingfor1year: "no",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },

      {
        title: "advancedPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 10 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 5 Pages",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
      {
        title: "enterprisePackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 20 Pages",
        Updateandaddpages: "yes",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 10 Pages",
        ProfessionalLogDesign: "yes",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
    ],
  },
  {
    title: "service4",
    packages: [
      {
        title: "starterPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 5 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "no",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "no",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "no",
        WebsiteVisitorStatistics: "no",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "no",
        EmailAddresses: "no",
        FreeDomainNamefor1year: "no",
        FreeWebsitehostingfor1year: "no",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },

      {
        title: "advancedPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 10 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 5 Pages",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
      {
        title: "enterprisePackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 20 Pages",
        Updateandaddpages: "yes",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 10 Pages",
        ProfessionalLogDesign: "yes",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
    ],
  },
  {
    title: "service5",
    packages: [
      {
        title: "starterPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 5 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "no",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "no",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "no",
        WebsiteVisitorStatistics: "no",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "no",
        EmailAddresses: "no",
        FreeDomainNamefor1year: "no",
        FreeWebsitehostingfor1year: "no",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },

      {
        title: "advancedPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 10 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 5 Pages",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
      {
        title: "enterprisePackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 20 Pages",
        Updateandaddpages: "yes",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 10 Pages",
        ProfessionalLogDesign: "yes",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
    ],
  },
  {
    title: "service6",
    packages: [
      {
        title: "starterPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 5 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "no",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "no",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "no",
        WebsiteVisitorStatistics: "no",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "no",
        EmailAddresses: "no",
        FreeDomainNamefor1year: "no",
        FreeWebsitehostingfor1year: "no",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },

      {
        title: "advancedPackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 10 Pages",
        Updateandaddpages: "no",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 5 Pages",
        ProfessionalLogDesign: "no",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
      {
        title: "enterprisePackage",
        CustomDesign: "yes",
        ChoiceofLayout: "yes",
        NumberofPagesIncluded: "Upto 20 Pages",
        Updateandaddpages: "yes",
        MobileFriendlyDesign: "yes",
        HomepageBannerDesigns: "Upto 10 Pages",
        ProfessionalLogDesign: "yes",
        SearchEngineFriendly: "yes",
        SearchEngineSubmission: "yes",
        WebsiteContactForm: "yes",
        SearchEngineOptimisation: "yes",
        WebsiteVisitorStatistics: "yes",
        FullWebsiteOwnership: "yes",
        GoogleMapsIntegration: "yes",
        SSDDiskSpace: "yes",
        EmailAddresses: "yes",
        FreeDomainNamefor1year: "yes",
        FreeWebsitehostingfor1year: "yes",
        PhoneandEmailSupport: "yes",
        BuiltInHouse: "yes",
      },
    ],
  }
];

const PricingCard = () => {
  return <div></div>;
};

export default PricingCard;
